const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

module.exports.generatePDF = (project) => {
    return new Promise((resolve, reject) => {
        try {
            // Ensure folders exist
            const exportDir = path.join(__dirname, 'files');
            if (!fs.existsSync(exportDir)) {
                fs.mkdirSync(exportDir, { recursive: true });
            }

            // File path
            const fileName = `${project.projectName.replace(/\s/g, '_')}_${Date.now()}.pdf`;
            const filePath = path.join(exportDir, fileName);

            const doc = new PDFDocument({ margin: 50 });
            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            // =========================
            // Document Header
            // =========================
            doc.fontSize(22).text('System Requirement Specification (SRS)', { align: 'center' });
            doc.moveDown();
            doc.fontSize(16).text(`Project Name: ${project.projectName}`, { underline: true });
            doc.moveDown(2);

            // =========================
            // Requirements Sections
            // =========================
            const requirements = project.requirements || {};

            Object.keys(requirements).forEach((section) => {
                doc.fontSize(14).text(section.toUpperCase(), { underline: true });
                doc.moveDown(0.5);

                if (Array.isArray(requirements[section])) {
                    requirements[section].forEach((item, index) => {
                        doc.fontSize(11).text(`${index + 1}. ${item}`);
                    });
                }
                doc.moveDown(1.5);
            });

            doc.fontSize(10).text('Generated by ReqForge', { align: 'center' });
            doc.end();

            stream.on('finish', () => resolve(filePath));
            stream.on('error', (err) => reject(err));

        } catch (error) {
            reject(error);
        }
    });
};
